=== HaykA/hibernate.projectizer/src/main/webapp/xsd/header.xsd
<?xml version="1.0"?>

<xs:schema id="header"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:pro="http://www.projectizer.com/header"
  targetNamespace="http://www.projectizer.com/header"
  elementFormDefault="qualified">
  
  <xs:complexType name="_entry">
    <xs:all>
      <xs:element name="key" type="xs:string"/>
      <xs:element name="value" type="xs:string"/>
    </xs:all>
  </xs:complexType>
  
  <xs:complexType name="_map">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="entry" type="pro:_entry"/>  
    </xs:sequence>
  </xs:complexType>
    
  <xs:element name="header">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="map" type="pro:_map"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== HaykA/hibernate.projectizer/src/main/webapp/xsd/header.xml
<?xml version="1.0" encoding="UTF-8"?>
<header xmlns="http://www.projectizer.com/header"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.projectizer.com/header header.xsd">
  <map>
    <entry>
      <key>Settings</key>
      <value>Settings</value>
    </entry>
    <entry>
      <key>Performance</key>
      <value>Performance</value>
    </entry>
  </map>
</header>
